# Generated by Django 5.1.3 on 2024-11-27 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_id_alter_studentfee_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='valid_until',
            field=models.DateField(default=datetime.date(2024, 12, 1), verbose_name='Valid Until'),
        ),
    ]
