# Generated by Django 5.1.3 on 2024-11-27 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersalary',
            name='valid_until',
            field=models.DateField(default=datetime.date(2024, 12, 1), verbose_name='Valid Until'),
        ),
    ]
