apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DJANGO_ALLOWED_HOSTS: {{ .Values.configMap.djangoAllowedHosts | quote }}
  DEBUG: {{ .Values.configMap.debug | quote }}