apiVersion: v1
kind: Service
metadata:
  name: easy-school
  namespace: easy-school
spec:
  selector:
    app: easy-school           # Matches deployment labels
  ports:
    - port: 80                   # Port the service listens on
      targetPort: 8000          # Port on your container
  type: LoadBalancer          # Makes service accessible externally